### PR TITLE
java.util.Base64 support

### PR DESCRIPTION
**Pull request by lbrasseur**
java.util.Base64 downloaded and modified from here:

http://grepcode.com/file_/repository.grepcode.com/java/root/jdk/openjdk/8-b132/java/util/Base64.java/?v=source

### CODE REVIEW

**Comment by konsoletyper** [comment]
I can't accept code from OpenJDK without legal issues.

**Comment by lbrasseur** [comment]
GNI classpath would be a problem too? Looking into Apache Harmony would be better?

**Comment by lbrasseur** [comment]
I meant, GNU Classpath

**Comment by konsoletyper** [comment]
Apache Harmony is under Apache license, which is ok (TeaVM is also under Apache 2.0). I guess GNU classpath is under (L)GPL, which is incompatible with Apache 2.0.

**Comment by lbrasseur** [comment]
Thanks! I will search there

**Pull request closed without merging**
