### PR TITLE
Hashmap foreach

### PR DESCRIPTION
**Pull request by Ihromant**

### CODE REVIEW

**Comment by konsoletyper** [comment]
Won't this PR affect LinkedHashMap order? I think `foreach` method should be overridden for this class as well.

**Comment by Ihromant** [comment]
Added override, removed unused import from HashMap

**Comment by konsoletyper** [comment]
BTW, looks like you copied this code from OpenJDK

**Comment by konsoletyper** [comment]
Also, did you run checkstyle checks? This code looks like improperly formatted

**Pull request closed without merging**
