### PR TITLE
Add timezone

### PR DESCRIPTION
**Pull request by shannah**

### CODE REVIEW

**Comment by konsoletyper** [comment]
Can you format code according to TeaVM standards? I know there isn't formal description yet, but you could at least copy style from existing code snippets. Did you actuall run tests in the browser? Did they all pass? Do you know how to run them?

**Comment by shannah** [comment]
I'll look through the code and try to reformat it to resemble teavm formatting.

The tests pass using mvn test.  I don't know how to run them in the browser but they initially failed with mvn test so I think it must be legitimately passing now.

**Comment by konsoletyper** [comment]
After full build go to `teavm-tests/target/javascript-test` and open `junit.html`. Sorry, I still did not integrate test run into maven build process. I have to fix existing tests (6 of them fail for now) in order to do this. Also, TeaVM only supports Junit 4 style tests. Please, avoid inheriting `TestCase` and don't forget to place `@Test` annotations.

**Comment by shannah** [comment]
Can you give me an example of the types of style changes that are needed.  I just took a quick look on my phone, and other than the method naming conventions in the tests, nothing is really jumping out at me.

**Comment by konsoletyper** [comment]
1. Please, use your full name in copyright header. It's legall stuff, so I belive the real name is preferrable over your system username.
2. Separate opening curly brace (`{`) from the prevous character with one whitespace, i.e. write `if (condition) {` rather than `if (condition){`.
3. Don't separate methods from each other with more than one empty line.
4. Prefer don't leave empty lines at the beginning or the end of a curly brace blocks, especially inside methods' bodies.

**Pull request merged**
