### PR TITLE
Support for default and static methods in Functors

### PR DESCRIPTION
**Pull request by marciodel**
This pull request implements the enhancement #279 .

### CODE REVIEW

**Comment by marciodel** [comment]
@konsoletyper, I've closed the Pull request with the same name for the branch 0.4.x and created this new one for master branch.

**Comment by konsoletyper** [comment]
Can you please provide tests? I suggest `org.teavm.jso.test.FunctorTest` class, which already tests `JsFunctor` behaviour.

**Comment by marciodel** [comment]
Sure. Do you want me to replace the Pull Request? Or add another one?

**Comment by konsoletyper** [comment]
You can add another commit, can't you?

**Comment by marciodel** [comment]
I don't know. I'll investigate it.

**Comment by marciodel** [comment]
I'm having problems with the local tests. All native tests are generating errors because of java.lang.UnsatisfiedLinkError. Did I miss something?

```
  AnnotationsTest.abstractWrapperWorks:42 ╗ UnsatisfiedLink org.teavm.jso.test.A...
  AnnotationsTest.staticBodyWorks:32->add:-2 UnsatisfiedLink org.teavm.jso.test....
  AnnotationsTest.memberBodyWorks:37->convert:-2 UnsatisfiedLink org.teavm.jso.t...
  AnnotationsTest.interfaceWrapperWorks:51->createWrapper:-2 UnsatisfiedLink org...
  ConversionTest.convertsPrimitiveArrays4ToJava:108->getPrimitiveArrays4:-2 UnsatisfiedLink
  ConversionTest.copiesArray:140->mutate:-2 UnsatisfiedLink org.teavm.jso.test.C...
  ConversionTest.convertsPrimitivesToJava:38->getPrimitives:-2 UnsatisfiedLink o...
  ConversionTest.convertsPrimitiveArrays4ToJavaScript:100->combinePrimitiveArrays4:-2 UnsatisfiedLink
  ConversionTest.convertsArrayOfJSObject:131 ╗ UnsatisfiedLink org.teavm.jso.cor...
  ConversionTest.convertsPrimitiveArraysToJavaScript:51->combinePrimitiveArrays:-2 UnsatisfiedLink
  ConversionTest.convertsPrimitiveArrays2ToJavaScript:75->combinePrimitiveArrays2:-2 UnsatisfiedLink
  ConversionTest.convertsPrimitiveArrays2ToJava:82->getPrimitiveArrays2:-2 UnsatisfiedLink
  ConversionTest.convertsPrimitivesToJavaScript:32->combinePrimitives:-2 UnsatisfiedLink
  ConversionTest.passesJSObject:126 ╗ UnsatisfiedLink org.teavm.jso.core.JSStrin...
  ConversionTest.convertsPrimitiveArraysToJava:58->getPrimitiveArrays:-2 UnsatisfiedLink
  FunctorTest.functorIdentityPreserved:37->getFunction:-2 UnsatisfiedLink org.te...
  FunctorTest.functorPassed:31->testMethod:-2 UnsatisfiedLink org.teavm.jso.test...
  JavaInvocationTest.callMemberMethod:35 ╗ UnsatisfiedLink org.teavm.jso.test.Ja...
  JavaInvocationTest.callStaticMethod:30->staticInvocation:-2 UnsatisfiedLink or...
```

**Comment by konsoletyper** [comment]
How do you run these tests?

**Comment by konsoletyper** [comment]
BTW, you can chat with me in [gitter](https://gitter.im/teavm/Lobby)

**Comment by marciodel** [comment]
mvn clean install

**Comment by konsoletyper** [comment]
Do you run `mvn clean install` on entire project, or on single `teavm-tests` module?

**Comment by konsoletyper** [comment]
It's strange. Looks like for some reason JUnit tries to run tests in JVM, while these tests have JVM suppressed by `@SkipJVM` annotation. I can't help you there, since I can't reproduce this issue. You should debug yourself or help me to reproduce this error.

**Comment by konsoletyper** [comment]
Merged manually

**Pull request closed without merging**
