### PR TITLE
#431: Add support for char annotation methods

### LINKED ISSUE #431: Parser.parseAnnotationValue fails on annotation methods returning char
When an annotation has a method returning `char`, TeaVM 0.6.0 throws `AssertionError`.

### PR DESCRIPTION
**Pull request by fluorumlabs**
Fixes #431

### CODE REVIEW

**Comment by fluorumlabs** [comment]
I modified `MetaprogrammingTest.annotationsWork` test, but, for some reason it was passing even for failing assertion. I was running it with `mvn test -Dtest=MetaprogrammingTest`, and in generated `js` files I see the correct expected/actual values. No idea if it's my setup failing, or something else is wrong.

**Comment by konsoletyper** [comment]
I'm afraid this commit is incomplete. You should support these methods in `AnnotationIO` and `ModelUtils.copyAnnotationValue`.

**Comment by fluorumlabs** [comment]
I knew I missed something :) Will do.

**Comment by fluorumlabs** [comment]
Could you please elaborate a bit? I added support for `CHAR` both to `AnnotationIO.writeAnnotationValue` and `AnnotationIO.readAnnotationValue`. `ModelUtil.copyAnnotationValue` however, does not care about primitive types:

```java
    private static AnnotationValue copyAnnotationValue(AnnotationValue value) {
        switch (value.getType()) {
            case AnnotationValue.LIST: {
                List<AnnotationValue> listCopy = new ArrayList<>();
                for (AnnotationValue item : value.getList()) {
                    listCopy.add(copyAnnotationValue(item));
                }
                return new AnnotationValue(listCopy);
            }
            case AnnotationValue.ANNOTATION:
                return new AnnotationValue(copyAnnotation(value.getAnnotation()));
            default:
                return value;
        }
    }
```

**Comment by konsoletyper** [comment]
Ah, you right. You don't need to copy primitive annotation values

**Pull request merged**
