### PR TITLE
Fix JavaScript generation for default methods which override other default methods

### PR DESCRIPTION
**Pull request by JojOatXGME**
At my company we had the problem that *TeaVM* generates incorrect JavaScript in some cases. We were able to fix the issue by ourselves in commit 8c5b10be9f1 but we have trouble to make the tests work correctly.

There are two similar bugs which occur in two different scenarios. Both bugs might occur when a default method of some interface overrides the default method of another interface. In both cases, the wrong method is called.

* The first bug occurs when the first path to the base interface does not contain the interface overriding the method.
* The second bug occurs when the interface overriding the method is only reachable over a super class.

Both cases are [demonstrated in commit 3ed067b4059](https://github.com/konsoletyper/teavm/blob/3ed067b405940c2cb97acb6ff502baabb62a3e2b/tests/src/test/java/org/teavm/vm/VMTest.java#L492-L527).

The test `VMTest.indirectDefaultMethod` already exists in previous commits but doesn't fail. The test does not detect the issue because some optimizations obscure the bug. In commit 3ed067b4059, I made some changes to prevent the *devirtualization*. As a result, you can see incorrect metadata generated for `$rt_metadata` in `tests/target/js-tests/org/teavm/vm/VMTest/indirectDefaultMethod/test.js`.

```
otv_VMTest$PathJoint, 0, jl_Object, [otv_VMTest$FirstPath, otv_VMTest$SecondPath], 0, 0, 0, 0, ["$_init_1", $rt_wrapFunction1(otv_VMTest$PathJoint__init_0), "$foo", $rt_wrapFunction0(otv_VMTest$FirstPath_foo)],
```

Unfortunately, the tests still cannot detect the bugs. Some other optimizations seem to obscure them in `test-optimized.js`. My best bet is that only the optimized file is executed. We should prevent the optimizations from obscuring the bugs. Any idea how we can achieve that? Do you have any other objections or suggestions for this pull request?

---

**PS:** I am executing the tests with `mvn -pl tests -e clean test [-Dtest=VMTest]`. When I try to run all tests with `mvn -e clean test`, some goal always fails with a `ClassNotFoundException`.

<details><summary>Full stacktrace</summary>

```
[ERROR] Failed to execute goal org.teavm:teavm-maven-plugin:0.7.0-SNAPSHOT:compile (compile-deobfuscator) on project teavm-junit: Unexpected error occurred: com/carrotsearch/hppc/ObjectIntMap: com.carrotsearch.hppc.ObjectIntMap -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.teavm:teavm-maven-plugin:0.7.0-SNAPSHOT:compile (compile-deobfuscator) on project teavm-junit: Unexpected error occurred
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unexpected error occurred
    at org.teavm.maven.TeaVMCompileMojo.executeWithBuilder (TeaVMCompileMojo.java:303)
    at org.teavm.maven.TeaVMCompileMojo.execute (TeaVMCompileMojo.java:246)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
Caused by: java.lang.NoClassDefFoundError: com/carrotsearch/hppc/ObjectIntMap
    at org.teavm.tooling.TeaVMTool.prepareJavaScriptTarget (TeaVMTool.java:313)
    at org.teavm.tooling.TeaVMTool.prepareTarget (TeaVMTool.java:303)
    at org.teavm.tooling.TeaVMTool.generate (TeaVMTool.java:353)
    at org.teavm.tooling.builder.InProcessBuildStrategy.build (InProcessBuildStrategy.java:261)
    at org.teavm.maven.TeaVMCompileMojo.executeWithBuilder (TeaVMCompileMojo.java:297)
    at org.teavm.maven.TeaVMCompileMojo.execute (TeaVMCompileMojo.java:246)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
Caused by: java.lang.ClassNotFoundException: com.carrotsearch.hppc.ObjectIntMap
    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass (SelfFirstStrategy.java:50)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass (ClassRealm.java:271)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass (ClassRealm.java:247)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass (ClassRealm.java:239)
    at org.teavm.tooling.TeaVMTool.prepareJavaScriptTarget (TeaVMTool.java:313)
    at org.teavm.tooling.TeaVMTool.prepareTarget (TeaVMTool.java:303)
    at org.teavm.tooling.TeaVMTool.generate (TeaVMTool.java:353)
    at org.teavm.tooling.builder.InProcessBuildStrategy.build (InProcessBuildStrategy.java:261)
    at org.teavm.maven.TeaVMCompileMojo.executeWithBuilder (TeaVMCompileMojo.java:297)
    at org.teavm.maven.TeaVMCompileMojo.execute (TeaVMCompileMojo.java:246)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
```

</details>

### CODE REVIEW

**Comment by konsoletyper** [comment]
> I am executing the tests with mvn -pl tests -e clean test [-Dtest=VMTest]. When I try to run all tests with mvn -e clean test, some goal always fails with a ClassNotFoundException.

Have no idea. Did you try adding '-am' option as well? I never run tests like that. I use two distinct ways:

1. Create run configuration in IDEA (with following run parameters: `-ea -Dteavm.junit.target=target/js-tests -Dteavm.junit.js.runner=browser-chrome -Dteavm.junit.threads=3 -Dteavm.junit.js.decodeStack=true`)
2. Run entire project build (I added `build-all.sh` script in recent commits).

**Comment by konsoletyper** [comment]
> I made some changes to prevent the devirtualization

There's no need in that, since default compilation settings disable devirtualization. Are you sure test actually runs in the browser or in Rhino?

**Comment by JojOatXGME** [comment]
> There's no need in that, since default compilation settings disable devirtualization.

In issue #224, you mention that devirtualization is enabled for optimization level `SIMPLE`. Anyway, it might also be another optimization causing the problem. As soon as I remove the following line from the tests,

```java
new FirstPathOptimizationPrevention().foo();
```

the method `FirstPath.foo()` is no longer part of the generated JavaScript and the metadata points to `SecondPath.foo()` (which would be right if there were no bug.

> Are you sure test actually runs in the browser or in Rhino?

Maven does not report any errors while running `mvn -pl tests -e clean test -Dtest=VMTest`. Not sure what it is doing there. The run parameters for the IDEA configuration you suggested earlier do not work for me. I get the following error

    Unknown lifecycle phase "a". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>

I'm not that familiar with Maven, unfortunately. Your built script also did not work. I guess it is failing to launch Chrome? Do I have to make some initial setup?

<details><summary>Exception</summary>

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test (default-test) on project teavm-html4j: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test failed: java.lang.RuntimeException: null,null,null,null,null: source is null -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test (default-test) on project teavm-html4j: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test failed: java.lang.RuntimeException: null,null,null,null,null
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test failed: java.lang.RuntimeException: null,null,null,null,null
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:148)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: null,null,null,null,null
    at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer.close (ThreadedStreamConsumer.java:123)
    at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork (ForkStarter.java:463)
    at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork (ForkStarter.java:352)
    at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run (ForkStarter.java:158)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider (AbstractSurefireMojo.java:958)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked (AbstractSurefireMojo.java:822)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute (AbstractSurefireMojo.java:720)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
Caused by: java.lang.RuntimeException: null,null,null,null,null
    at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.createReportEntry (ForkClient.java:210)
    at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.consumeLine (ForkClient.java:105)
    at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer$Pumper.run (ThreadedStreamConsumer.java:67)
    at java.lang.Thread.run (Thread.java:834)
Caused by: java.lang.NullPointerException: source is null
    at org.apache.maven.surefire.report.SimpleReportEntry.<init> (SimpleReportEntry.java:58)
    at org.apache.maven.surefire.report.CategorizedReportEntry.reportEntry (CategorizedReportEntry.java:57)
    at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.createReportEntry (ForkClient.java:206)
    at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.consumeLine (ForkClient.java:105)
    at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer$Pumper.run (ThreadedStreamConsumer.java:67)
    at java.lang.Thread.run (Thread.java:834)
```

</details>

**Comment by konsoletyper** [comment]
> The run parameters for the IDEA configuration you suggested earlier do not work for me. 

It's run parameters for JUnit launch configuration in IDEA.

> Maven does not report any errors while running mvn -pl tests -e clean test -Dtest=VMTest

It not necessarily has. If you don't provide right configuration for JUnit, it assumes that you don't need to run tests in actual browser and will only run them in JVM, without reporting any errors.

**Comment by konsoletyper** [comment]
> In issue #224, you mention that devirtualization is enabled for optimization level SIMPLE

That was more than 4 years ago. This could change since then. I'll double check SIMPLE optimizations. But since I introduced dev server with incremental compilation, I reconsidered which optimizations to do at SIMPLE level. Devirtualization, like all other global optimizations, is not friendly to incremental compilation, so I had to disable it on SIMPLE level.

**Comment by konsoletyper** [comment]
>Your built script also did not work. I guess it is failing to launch Chrome? Do I have to make some initial setup?

It's a weird issue. I don't know why it occurs, but it's somewhere deep in Maven internals, not in TeaVM.

**Comment by konsoletyper** [comment]
Merged

**Comment by JojOatXGME** [comment]
Thanks for merging and your help with my test configuration.

> That was more than 4 years ago. This could change since then. I'll double check SIMPLE optimizations. But since I introduced dev server with incremental compilation, I reconsidered which optimizations to do at SIMPLE level. Devirtualization, like all other global optimizations, is not friendly to incremental compilation, so I had to disable it on SIMPLE level.

Ok. Then it is something else.

> > The run parameters for the IDEA configuration you suggested earlier do not work for me.
> 
> It's run parameters for JUnit launch configuration in IDEA.

This makes sense. It works now. I just had to rename `chrome.exe` to `google-chrome-stable.exe` (I am on Windows) and add it to the `Path`.

> > Your built script also did not work. I guess it is failing to launch Chrome? Do I have to make some initial setup?
> 
> It's a weird issue. I don't know why it occurs, but it's somewhere deep in Maven internals, not in TeaVM.

I should have mentioned that the error occurred after the following line in the output.

    Running chrome with user data dir: C:\Users\JOHANN~1\AppData\Local\Temp\teavm321531291335167255teavm

It seems to work now. Maybe because I made `google-chrome-stable.exe` available in the `Path`. Beside that, there are a lot of other tests failing on my system.

```
Results :

Tests in error: 
  DecimalFormatParseTest.parsesSpecial Â» Runtime java.text.ParseException: Unpar...
  DecimalFormatTest.formatsSpecialValues Â» Runtime org.junit.ComparisonFailure: ...
  DecimalFormatTest.formatsSpecial Â» Runtime org.junit.ComparisonFailure: expect...
  NumberFormatTest.formatsNumber Â» Runtime org.junit.ComparisonFailure: expected...
  NumberFormatTest.formatsCurrency Â» Runtime org.junit.ComparisonFailure: expect...
  NumberFormatTest.formatsPercent Â» Runtime org.junit.ComparisonFailure: expecte...
  CurrencyTest.getsDisplayName Â» Runtime org.junit.ComparisonFailure: expected:<...
  CurrencyTest.getsSymbol Â» Runtime org.junit.ComparisonFailure: expected:<[â‚½]> ...
  LocaleTest.countryNamesProvided Â» Runtime org.junit.ComparisonFailure: expecte...
  LocaleTest.languageNamesProvided Â» Runtime org.junit.ComparisonFailure: expect...
```

They look like there is a problem with the encoding. Maybe the tests fail on my system but not on yours because the default encoding is different on Windows?

```
java.lang.RuntimeException: java.text.ParseException: Unparseable number: ∞
java.lang.RuntimeException: org.junit.ComparisonFailure: expected:<230[‰]> but was:<230[â]>
java.lang.RuntimeException: org.junit.ComparisonFailure: expected:<[∞]> but was:<[âˆž]>
java.lang.RuntimeException: org.junit.ComparisonFailure: expected:<123[ ]456,789> but was:<123[Â]456,789>
java.lang.RuntimeException: org.junit.ComparisonFailure: expected:<[]RUB123,456.79> but was:<[Â]RUB123,456.79>
java.lang.RuntimeException: org.junit.ComparisonFailure: expected:<12[ 345 679] %> but was:<12[Â345Â679Â] %>
java.lang.RuntimeException: org.junit.ComparisonFailure: expected:<[доллар сша]> but was:<[ð´ð¾ð»ð»ð°ñ€ ð¡ð¨ð�]>
java.lang.RuntimeException: org.junit.ComparisonFailure: expected:<[₽]> but was:<[â‚½]>
java.lang.RuntimeException: org.junit.ComparisonFailure: expected:<[Соединенные Штаты]> but was:<[Ð¡Ð¾ÐµÐ´Ð¸Ð½ÐµÐ½Ð½Ñ‹Ðµ Ð¨Ñ‚Ð°Ñ‚Ñ‹]>
java.lang.RuntimeException: org.junit.ComparisonFailure: expected:<[английский]> but was:<[Ð°Ð½Ð³Ð»Ð¸Ð¹Ñ�ÐºÐ¸Ð¹]>
```

This encoding issue is not very important for us right now. Should I still create an issue for that?

**Pull request closed without merging**
